services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    ports:
      - "8200:8000"
    volumes:
      - ./src/backend:/app/app
      - ./data:/data
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
        
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    #environment:
    #  VITE_API_BASE_URL=http://localhost:5173/ #what is "vite"?
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - app

volumes:
  pgdata: