<script setup lang="ts">
import { ref, onMounted } from "vue";
import { currentUser } from "../../state/auth";
import { fetchLibraryExport, importLibrary, fetchBackupStatus, exportDeploymentBackup, restoreDeploymentBackup, rotateDeploymentKey } from "../../services/exportImport";
import type { ImportResult, BackupStatus } from "../../services/exportImport";

const backupStatus = ref<BackupStatus | null>(null);
onMounted(async () => { try { backupStatus.value = await fetchBackupStatus(); } catch { /* optional */ } });
function formatBackupDate(epochSeconds: number): string { return new Date(epochSeconds * 1000).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }); }

const exporting = ref(false); const exportError = ref<string | null>(null);
async function exportLibrary() { exporting.value = true; exportError.value = null; try { const data = await fetchLibraryExport(); const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `library-export-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); } catch (err) { exportError.value = err instanceof Error ? err.message : "Failed to export library"; } finally { exporting.value = false; } }
const importing = ref(false); const importError = ref<string | null>(null); const importResult = ref<ImportResult | null>(null);
async function onFileSelected(e: Event) { const input = e.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; importing.value = true; importError.value = null; importResult.value = null; try { const parsed = JSON.parse(await file.text()); const games = Array.isArray(parsed) ? parsed : parsed.games; if (!Array.isArray(games)) throw new Error('This file doesn\'t look like a library export, expected a "games" list.'); importResult.value = await importLibrary(games); } catch (err) { importError.value = err instanceof Error ? err.message : "Failed to import library"; } finally { importing.value = false; input.value = ""; } }

const deploymentExportPassword = ref(""); const deploymentExportPasswordConfirm = ref(""); const deploymentImportPassword = ref("");
const deploymentExporting = ref(false); const deploymentRestoring = ref(false); const deploymentRotating = ref(false); const deploymentError = ref<string | null>(null); const deploymentMessage = ref<string | null>(null);
function validateBackupPassword(password: string, confirmation?: string) { if (password.length < 12) throw new Error("Backup passwords must be at least 12 characters."); if (confirmation !== undefined && password !== confirmation) throw new Error("Backup passwords do not match."); }
async function exportDeployment() { deploymentExporting.value = true; deploymentError.value = null; deploymentMessage.value = null; try { validateBackupPassword(deploymentExportPassword.value, deploymentExportPasswordConfirm.value); const blob = await exportDeploymentBackup(deploymentExportPassword.value); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `archive-deployment-backup-${new Date().toISOString().replace(/[:.]/g, "-")}.json`; link.click(); URL.revokeObjectURL(url); deploymentMessage.value = "Encrypted deployment backup downloaded. Keep the backup and its password separate."; } catch (err) { deploymentError.value = err instanceof Error ? err.message : "Failed to export deployment backup"; } finally { deploymentExporting.value = false; } }
const restoreInput = ref<HTMLInputElement | null>(null);
async function restoreDeployment(e: Event) { const input = e.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; deploymentRestoring.value = true; deploymentError.value = null; deploymentMessage.value = null; try { validateBackupPassword(deploymentImportPassword.value); if (!window.confirm("Restore deployment configuration and secrets? This will replace deployment settings and invalidate every active login session. User accounts, libraries, and media will not be imported.")) return; const result = await restoreDeploymentBackup(file, deploymentImportPassword.value); deploymentMessage.value = result.message; window.setTimeout(() => window.location.reload(), 1500); } catch (err) { deploymentError.value = err instanceof Error ? err.message : "Failed to restore deployment backup"; } finally { deploymentRestoring.value = false; input.value = ""; } }
async function rotateKey() { if (!window.confirm("Rotate the Fernet encryption key now? All users will be signed out and all stored application secrets will be re-encrypted.")) return; deploymentRotating.value = true; deploymentError.value = null; deploymentMessage.value = null; try { const result = await rotateDeploymentKey(); deploymentMessage.value = result.message; window.setTimeout(() => window.location.reload(), 1500); } catch (err) { deploymentError.value = err instanceof Error ? err.message : "Failed to rotate encryption key"; } finally { deploymentRotating.value = false; } }
</script>

<template>
  <section class="settings-section">
    <h2>Export / Import</h2>
    <p class="section-hint">A portable JSON snapshot of your games, for backups or moving to a new server. This covers game data and metadata only, not attached files (screenshots, saves, docs) or bounties.</p>
    <div v-if="backupStatus" class="tile backup-status-tile"><h3>Automatic backups</h3><p class="tile-desc">A snapshot is written automatically every {{ backupStatus.interval_hours }} hours, keeping the last {{ backupStatus.backups_kept }} on this server.</p><p class="backup-status-line"><span v-if="backupStatus.last_backup_at">Last backup {{ formatBackupDate(backupStatus.last_backup_at) }} · {{ backupStatus.backup_count }} kept</span><span v-else>No backup yet; the first one is written within {{ backupStatus.interval_hours }} hours.</span></p></div>
    <div class="tile"><h3>Export</h3><p class="tile-desc">Downloads every game in your library as a single JSON file.</p><div v-if="exportError" class="form-error">{{ exportError }}</div><button type="button" class="primary-button" :disabled="exporting" @click="exportLibrary">{{ exporting ? "Exporting…" : "Export library" }}</button></div>
    <div class="tile"><h3>Import</h3><p class="tile-desc">Add games from a previously exported file. Existing games are never overwritten.</p><div v-if="importError" class="form-error">{{ importError }}</div><div v-if="importResult" class="form-success">Imported {{ importResult.created }} game{{ importResult.created === 1 ? "" : "s" }}. <template v-if="importResult.skipped">{{ importResult.skipped }} skipped.</template></div><label class="secondary-button upload-label">{{ importing ? "Importing…" : "Choose file…" }}<input type="file" accept="application/json" class="hidden-input" :disabled="importing" @change="onFileSelected" /></label></div>

    <div v-if="currentUser?.is_admin" class="tile security-tile">
      <h3>Deployment configuration backup</h3>
      <p class="tile-desc">Admin-only migration backup containing deployment settings, provider/SMTP/OIDC secrets, and the three persistent Fernet key copies. It excludes users, sessions, user API keys, libraries, media, and other user data. The downloaded archive is encrypted with a password you provide.</p>
      <div v-if="deploymentError" class="form-error">{{ deploymentError }}</div><div v-if="deploymentMessage" class="form-success">{{ deploymentMessage }}</div>
      <div class="form-grid"><label>Backup password<input v-model="deploymentExportPassword" type="password" autocomplete="new-password" minlength="12" placeholder="At least 12 characters" /></label><label>Confirm password<input v-model="deploymentExportPasswordConfirm" type="password" autocomplete="new-password" minlength="12" /></label></div>
      <button type="button" class="primary-button" :disabled="deploymentExporting" @click="exportDeployment">{{ deploymentExporting ? "Encrypting…" : "Export deployment configuration" }}</button>
      <hr />
      <h3>Restore deployment configuration</h3><p class="tile-desc">Upload an encrypted deployment backup and enter its password. This restores deployment configuration only; it never imports user accounts or user data.</p>
      <label>Backup password<input v-model="deploymentImportPassword" type="password" autocomplete="current-password" minlength="12" /></label>
      <label class="secondary-button upload-label">{{ deploymentRestoring ? "Restoring…" : "Choose encrypted backup…" }}<input ref="restoreInput" type="file" accept="application/json" class="hidden-input" :disabled="deploymentRestoring" @change="restoreDeployment" /></label>
      <hr /><h3>Encryption key rotation</h3><p class="tile-desc">Generate a new Fernet key and re-encrypt all known stored secrets. The previous key is retained as decrypt-only recovery material until the next rotation. Everyone will be signed out.</p><button type="button" class="secondary-button" :disabled="deploymentRotating" @click="rotateKey">{{ deploymentRotating ? "Rotating…" : "Rotate encryption key" }}</button>
    </div>
  </section>
</template>

<style scoped>
.settings-section h2{margin:0 0 8px;padding-left:12px;border-left:3px solid #d68a34;font-size:1rem;color:#fff}.section-hint{color:#999;font-size:.82rem;line-height:1.6;margin:0 0 20px}.tile{background:#111;border:1px solid #2a2a2a;border-radius:10px;padding:18px 20px;margin-bottom:16px}.tile h3{margin:0 0 6px;font-size:.9rem;color:#fff}.tile-desc{color:#999;font-size:.8rem;line-height:1.5;margin:0 0 14px}.backup-status-tile{border-color:rgba(214,138,52,.3);background:rgba(214,138,52,.04)}.backup-status-line{margin:0;color:#d68a34;font-size:.78rem;font-weight:600}.primary-button{background:#d68a34;color:#111;border:none;border-radius:8px;padding:11px 20px;font-weight:600;cursor:pointer}.primary-button:disabled,.secondary-button:disabled{opacity:.6;cursor:not-allowed}.secondary-button{background:rgba(255,255,255,.08);color:#fff;border:none;border-radius:8px;padding:10px 16px;font-size:.82rem;font-weight:600;cursor:pointer}.upload-label{display:inline-block;cursor:pointer}.hidden-input{display:none}.form-error{color:#fca5a5;font-size:13px;background:rgba(220,38,38,.1);border:1px solid rgba(220,38,38,.3);border-radius:8px;padding:8px 10px;margin-bottom:12px}.form-success{color:#86efac;font-size:13px;background:rgba(34,197,94,.1);border:1px solid rgba(34,197,94,.3);border-radius:8px;padding:8px 10px;margin-bottom:12px}.security-tile{border-color:rgba(214,138,52,.35)}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px}.form-grid label,.security-tile>label{display:flex;flex-direction:column;gap:6px;color:#bbb;font-size:.78rem;margin-bottom:12px}.security-tile input{background:#191919;border:1px solid #333;border-radius:7px;color:#fff;padding:9px}.security-tile hr{border:0;border-top:1px solid #2a2a2a;margin:20px 0}@media(max-width:760px){.form-grid{grid-template-columns:1fr}}
</style>
