<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { fetchDeploymentSettings, updateDeploymentSettings } from "../../services/deploymentSettings";

const loading=ref(true);const saving=ref(false);const saved=ref(false);const error=ref<string|null>(null);
const smtp=reactive({enabled:false,host:"",port:587,username:"",password:"",use_tls:true,use_ssl:false,from_email:"",from_name:"Archive"});
onMounted(async()=>{try{const r=await fetchDeploymentSettings();const s=r.smtp;smtp.enabled=s.enabled;smtp.host=s.host??"";smtp.port=s.port??587;smtp.username=s.username??"";smtp.use_tls=s.use_tls;smtp.use_ssl=s.use_ssl;smtp.from_email=s.from_email??"";smtp.from_name=s.from_name??"";}catch(e){error.value=e instanceof Error?e.message:"Failed to load SMTP settings.";}finally{loading.value=false;}});
async function save(){saving.value=true;error.value=null;saved.value=false;try{await updateDeploymentSettings({smtp_enabled:String(smtp.enabled),smtp_host:smtp.host.trim(),smtp_port:String(smtp.port),smtp_username:smtp.username.trim(),smtp_use_tls:String(smtp.use_tls),smtp_use_ssl:String(smtp.use_ssl),smtp_from_email:smtp.from_email.trim(),smtp_from_name:smtp.from_name.trim(),...(smtp.password?{smtp_password:smtp.password}:{})});smtp.password="";saved.value=true;}catch(e){error.value=e instanceof Error?e.message:"Failed to save SMTP settings.";}finally{saving.value=false;}}
</script>
<template><section class="section"><h2>SMTP / Email</h2><p class="hint">Configure outbound email for password resets. The SMTP password is encrypted on the backend and never returned to the browser.</p><div v-if="loading">Loading…</div><template v-else><label class="toggle"><input v-model="smtp.enabled" type="checkbox"/><span>Enable SMTP email</span></label><div class="grid"><label><span>SMTP host</span><input v-model="smtp.host" placeholder="smtp.example.com"/></label><label><span>Port</span><input v-model.number="smtp.port" type="number" min="1" max="65535"/></label><label><span>Username</span><input v-model="smtp.username" autocomplete="off"/></label><label><span>Password</span><input v-model="smtp.password" type="password" autocomplete="new-password" :placeholder="'Leave blank to keep saved password'"/></label><label><span>Sender email</span><input v-model="smtp.from_email" type="email" placeholder="noreply@example.com"/></label><label><span>Sender name</span><input v-model="smtp.from_name"/></label></div><div class="checks"><label><input v-model="smtp.use_tls" type="checkbox"/> STARTTLS</label><label><input v-model="smtp.use_ssl" type="checkbox"/> SSL/TLS</label></div><p class="hint">Use STARTTLS for typical port 587 configurations. Use SSL/TLS for providers that expect an implicit TLS connection, commonly on port 465.</p><p v-if="error" class="error">{{error}}</p><p v-if="saved" class="success">SMTP settings saved.</p><button :disabled="saving" @click="save">{{saving?"Saving…":"Save SMTP settings"}}</button></template></section></template>
<style scoped>.section{display:flex;flex-direction:column;gap:16px}.hint{color:#999;font-size:13px;line-height:1.5}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid label{display:flex;flex-direction:column;gap:6px;color:#ccc;font-size:13px}.grid input{background:#111;border:1px solid #3a3a3a;border-radius:8px;color:#fff;padding:10px;font:inherit}.toggle,.checks label{display:flex;align-items:center;gap:8px;color:#ccc;font-size:13px}.toggle input,.checks input{accent-color:#d68a34}.checks{display:flex;gap:20px}.section button{background:#d68a34;border:0;border-radius:8px;padding:10px 14px;font-weight:600;cursor:pointer}.section button:disabled{opacity:.6}.error{color:#fca5a5}.success{color:#86efac}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style>
