<script setup lang="ts">
import { computed, ref } from "vue";
import { useRoute, useRouter } from "vue-router";

const route=useRoute(); const router=useRouter();
const token=computed(()=>typeof route.query.token==="string"?route.query.token:"");
const mode=ref(token.value?"reset":"request"); const identifier=ref(""); const password=ref(""); const confirm=ref("");
const message=ref<string|null>(null); const error=ref<string|null>(null); const loading=ref(false);
async function requestReset(){error.value=null;message.value=null;if(!identifier.value.trim()){error.value="Enter your username or email.";return;}loading.value=true;try{const r=await fetch("/api/auth/password-reset/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({identifier:identifier.value.trim()})});const data=await r.json();if(!r.ok)throw new Error(data.detail||"Unable to request a reset.");message.value=data.message;}catch(e){error.value=e instanceof Error?e.message:"Unable to request a reset.";}finally{loading.value=false;}}
async function resetPassword(){error.value=null;message.value=null;if(!token.value){error.value="This reset link is missing its token.";return;}if(password.value!==confirm.value){error.value="Passwords do not match.";return;}loading.value=true;try{const r=await fetch("/api/auth/password-reset/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:token.value,password:password.value})});const data=await r.json();if(!r.ok)throw new Error(data.detail||"Unable to reset password.");message.value=data.message;mode.value="request";}catch(e){error.value=e instanceof Error?e.message:"Unable to reset password.";}finally{loading.value=false;}}
function goLogin(){router.replace("/login");}
</script>
<template><main class="page"><form class="card" @submit.prevent="mode==='request'?requestReset():resetPassword"><div class="brand"><span>🎮</span><h1>Archive</h1></div><p class="subtitle">{{mode==='request'?"Reset your password":"Choose a new password"}}</p><template v-if="mode==='request'"><label><span>Username or email</span><input v-model="identifier" autocomplete="username" required /></label><p class="hint">If an account matches, we'll send a password reset link to its email address.</p></template><template v-else><label><span>New password</span><input v-model="password" type="password" autocomplete="new-password" minlength="9" required /></label><label><span>Confirm password</span><input v-model="confirm" type="password" autocomplete="new-password" minlength="9" required /></label><p class="hint">Use at least 9 characters with uppercase, lowercase, and a symbol.</p></template><p v-if="error" class="error">{{error}}</p><p v-if="message" class="success">{{message}}</p><button :disabled="loading">{{loading?(mode==='request'?"Sending…":"Resetting…"):(mode==='request'?"Send reset link":"Reset password")}}</button><button type="button" class="secondary" @click="goLogin">Back to sign in</button></form></main></template>
<style scoped>.page{min-height:100vh;display:flex;align-items:center;justify-content:center;background:#121212;font-family:system-ui,sans-serif;padding:24px}.card{width:100%;max-width:380px;background:#1a1a1a;border:1px solid #2a2a2a;border-radius:14px;padding:32px;display:flex;flex-direction:column;gap:14px}.brand{display:flex;align-items:center;gap:10px;justify-content:center;color:#fff}.brand h1{margin:0;font-size:1.4rem}.subtitle{margin:0;text-align:center;color:#aaa}.hint{color:#888;font-size:12px;line-height:1.5}.card label{display:flex;flex-direction:column;gap:6px;color:#ccc;font-size:13px}.card input{background:#111;border:1px solid #3a3a3a;border-radius:8px;color:#fff;padding:10px;font:inherit}.card input:focus{outline:none;border-color:#d68a34}.card button{background:#d68a34;border:0;border-radius:8px;padding:11px;font-weight:600;cursor:pointer}.card button:disabled{opacity:.6}.card button.secondary{background:#292929;color:#ddd}.error,.success{font-size:13px;padding:9px;border-radius:8px}.error{color:#fca5a5;background:rgba(220,38,38,.1);border:1px solid rgba(220,38,38,.3)}.success{color:#86efac;background:rgba(34,197,94,.08);border:1px solid rgba(34,197,94,.2)}</style>
