<script setup lang="ts">
import { ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { createInitialAdmin } from "../services/setup";
import { checkAuth } from "../state/auth";

const route=useRoute(); const router=useRouter();
const username=ref(""); const email=ref(""); const password=ref(""); const confirmPassword=ref("");
const oidcEnabled=ref(false); const oidcIssuer=ref(""); const oidcClientId=ref(""); const oidcClientSecret=ref("");
const oidcScopes=ref("openid profile email"); const oidcRedirectUri=ref(`${window.location.origin}/api/auth/oidc/callback`); const oidcGroupsClaim=ref("groups"); const oidcAdminGroup=ref(""); const oidcUserMatchField=ref("email");
const smtpEnabled=ref(false); const smtpHost=ref(""); const smtpPort=ref(587); const smtpUsername=ref(""); const smtpPassword=ref(""); const smtpUseTls=ref(true); const smtpUseSsl=ref(false); const smtpFromEmail=ref(""); const smtpFromName=ref("Archive");
const error=ref<string|null>(route.query.backend_error?"The frontend cannot reach the backend yet. Start the backend service, then reload this page.":null); const loading=ref(false);

async function submit(){
  error.value=null;
  if(password.value!==confirmPassword.value){error.value="Passwords do not match.";return;}
  if(oidcEnabled.value&&(!oidcIssuer.value.trim()||!oidcClientId.value.trim()||!oidcClientSecret.value)){error.value="OIDC requires an issuer URL, client ID, and client secret.";return;}
  if(smtpEnabled.value&&(!smtpHost.value.trim()||!smtpFromEmail.value.trim())){error.value="SMTP requires a host and sender email address.";return;}
  loading.value=true;
  try{await createInitialAdmin(username.value.trim(),email.value.trim(),password.value,{oidc_enabled:oidcEnabled.value,...(oidcEnabled.value?{oidc_issuer_url:oidcIssuer.value.trim(),oidc_client_id:oidcClientId.value.trim(),oidc_client_secret:oidcClientSecret.value,oidc_scopes:oidcScopes.value.trim(),oidc_redirect_uri:oidcRedirectUri.value.trim()||`${window.location.origin}/api/auth/oidc/callback`,oidc_groups_claim:oidcGroupsClaim.value.trim()||"groups",oidc_admin_group:oidcAdminGroup.value.trim(),oidc_user_match_field:oidcUserMatchField.value}:{}),smtp_enabled:smtpEnabled.value,...(smtpEnabled.value?{smtp_host:smtpHost.value.trim(),smtp_port:smtpPort.value,smtp_username:smtpUsername.value.trim(),smtp_password:smtpPassword.value,smtp_use_tls:smtpUseTls.value,smtp_use_ssl:smtpUseSsl.value,smtp_from_email:smtpFromEmail.value.trim(),smtp_from_name:smtpFromName.value.trim()}: {})});await checkAuth();await router.replace("/");}catch(err){error.value=err instanceof Error?err.message:"Setup failed.";}finally{loading.value=false;}
}
</script>
<template>
  <main class="setup-page"><form class="setup-card" @submit.prevent="submit">
    <div class="brand"><span>🎮</span><h1>Archive setup</h1></div><p class="subtitle">Create the administrator account for this installation.</p>
    <label><span>Username</span><input v-model="username" autocomplete="username" required /></label><label><span>Email</span><input v-model="email" type="email" autocomplete="email" required /></label><label><span>Password</span><input v-model="password" type="password" autocomplete="new-password" minlength="9" required /></label><label><span>Confirm password</span><input v-model="confirmPassword" type="password" autocomplete="new-password" minlength="9" required /></label><p class="hint">Use at least 9 characters with uppercase, lowercase, and a symbol.</p>
    <label class="toggle"><input v-model="oidcEnabled" type="checkbox" /><span>Configure OpenID Connect / SSO now</span></label>
    <div v-if="oidcEnabled" class="panel"><p class="hint">Optional. You can configure SSO later from Settings → OIDC / SSO.</p><label><span>Issuer URL</span><input v-model="oidcIssuer" /></label><label><span>Client ID</span><input v-model="oidcClientId" /></label><label><span>Client secret</span><input v-model="oidcClientSecret" type="password" /></label><label><span>Scopes</span><input v-model="oidcScopes" /></label><label><span>Redirect URI</span><input v-model="oidcRedirectUri" /></label><label><span>Groups claim</span><input v-model="oidcGroupsClaim" /></label><label><span>Admin group</span><input v-model="oidcAdminGroup" /></label><div class="match-options"><span class="match-title">Match existing users by</span><label class="radio"><input v-model="oidcUserMatchField" type="radio" value="email" /><span>Email</span></label><label class="radio"><input v-model="oidcUserMatchField" type="radio" value="username" /><span>Username</span></label></div></div>
    <label class="toggle"><input v-model="smtpEnabled" type="checkbox" /><span>Configure SMTP email now</span></label>
    <div v-if="smtpEnabled" class="panel"><p class="hint">Optional. SMTP enables password-reset emails. You can configure it later from Settings → SMTP / Email.</p><div class="two"><label><span>SMTP host</span><input v-model="smtpHost" placeholder="smtp.example.com" /></label><label><span>Port</span><input v-model.number="smtpPort" type="number" min="1" max="65535" /></label></div><div class="two"><label><span>Username</span><input v-model="smtpUsername" autocomplete="off" /></label><label><span>Password</span><input v-model="smtpPassword" type="password" autocomplete="new-password" /></label></div><div class="two"><label><span>Sender email</span><input v-model="smtpFromEmail" type="email" placeholder="noreply@example.com" /></label><label><span>Sender name</span><input v-model="smtpFromName" /></label></div><div class="checks"><label class="inline"><input v-model="smtpUseTls" type="checkbox" /> STARTTLS</label><label class="inline"><input v-model="smtpUseSsl" type="checkbox" /> SSL/TLS</label></div></div>
    <div v-if="error" class="error">{{ error }}</div><button :disabled="loading||Boolean(route.query.backend_error)">{{ loading?"Creating account…":"Create administrator" }}</button>
  </form></main>
</template>
<style scoped>
.setup-page{min-height:100vh;display:flex;align-items:center;justify-content:center;background:#121212;font-family:system-ui,sans-serif;padding:32px 16px}.setup-card{width:100%;max-width:500px;background:#1a1a1a;border:1px solid #2a2a2a;border-radius:14px;padding:32px;display:flex;flex-direction:column;gap:14px}.brand{display:flex;align-items:center;gap:10px;justify-content:center;color:#fff}.brand h1{font-size:1.4rem;margin:0}.subtitle,.hint{color:#999;font-size:13px;text-align:center}.hint{line-height:1.5;margin:0}.setup-card label{display:flex;flex-direction:column;gap:6px;color:#ccc;font-size:13px}.setup-card input{background:#111;border:1px solid #3a3a3a;border-radius:8px;color:#fff;padding:10px;font:inherit}.setup-card input:focus{outline:none;border-color:#d68a34}.toggle{flex-direction:row!important;align-items:center;padding-top:4px}.toggle input{width:16px;height:16px;accent-color:#d68a34}.panel{display:flex;flex-direction:column;gap:12px;padding:14px;border:1px solid #2f2f2f;border-radius:10px;background:#151515}.panel .hint{text-align:left}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.match-options{display:flex;flex-direction:column;gap:8px;padding:10px;border:1px solid #2f2f2f;border-radius:8px;background:#111}.match-title{color:#fff;font-size:13px;font-weight:600}.radio,.inline{flex-direction:row!important;align-items:center;gap:8px!important}.radio input,.inline input{width:16px;height:16px;accent-color:#d68a34}.checks{display:flex;gap:18px}.setup-card button{background:#d68a34;border:0;border-radius:8px;padding:11px;font-weight:600;cursor:pointer}.setup-card button:disabled{opacity:.6}.error{color:#fca5a5;background:rgba(220,38,38,.1);border:1px solid rgba(220,38,38,.3);border-radius:8px;padding:8px;font-size:13px}@media(max-width:600px){.two{grid-template-columns:1fr}}
</style>
