export const GENRE_OPTIONS = [
    'Action',
    'Adventure',
    'RPG',
    'Shooter',
    'Platformer',
    'Puzzle',
    'Strategy',
    'Simulation',
    'Sports',
    'Racing',
    'Fighting',
    'Horror',
    'Survival',
    'Stealth',
    'Sandbox',
    'Open World',
    'Metroidvania',
    'Roguelike',
    'Rhythm',
    'Visual Novel',
    'Party',
    'Card & Board',
    'MMO',
    'Tactics',
    'Educational',
]