"""added user table

Revision ID: 0284d11effb1
Revises: f59d16fccd48
Create Date: 2026-09-02 20:03:31.235958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0284d11effb1'
down_revision: Union[str, None] = 'f59d16fccd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('sort_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('runtime_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('director', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('writer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('studios', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.Column('countries', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.Column('age_rating', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tmdb_score', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('favorite', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rewatches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_story', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('rating_performance', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('rating_soundtrack', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('rating_overall', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('personal_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='movies_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
