"""Media

Revision ID: 31eac59c4107
Revises: f6bb4f914739
Create Date: 2026-09-21 03:29:03.578159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31eac59c4107'
down_revision: Union[str, None] = 'f6bb4f914739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_settings',
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('interval_minutes', sa.Integer(), server_default='1440', nullable=False),
    sa.Column('last_run_at', sa.BigInteger(), nullable=True),
    sa.Column('last_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.String(length=5), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=10), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_events_user_date', 'calendar_events', ['user_id', 'event_date'], unique=False)
    op.add_column('anime', sa.Column('title_english', sa.String(length=500), nullable=True))
    op.add_column('anime', sa.Column('title_romaji', sa.String(length=500), nullable=True))
    op.add_column('anime', sa.Column('title_native', sa.String(length=500), nullable=True))
    op.create_index('ix_anime_episodes_air_at', 'anime_episodes', ['air_at'], unique=False, postgresql_where=sa.text('air_at IS NOT NULL'))
    op.create_index('ix_anime_episodes_season_watched', 'anime_episodes', ['season_id', 'watched'], unique=False)
    op.create_unique_constraint('uq_anime_episodes_season_id_episode_number', 'anime_episodes', ['season_id', 'episode_number'])
    op.create_index('ix_cards_archive_number_user_active', 'cards', ['user_id', 'archive_number'], unique=True, postgresql_where=sa.text('archive_number IS NOT NULL'))
    op.create_index(op.f('ix_games_parent_game_id'), 'games', ['parent_game_id'], unique=False)
    op.add_column('media_lists', sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('media_lists', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_tv_episodes_air_at', 'tv_episodes', ['air_at'], unique=False, postgresql_where=sa.text('air_at IS NOT NULL'))
    op.create_index('ix_tv_episodes_season_watched', 'tv_episodes', ['season_id', 'watched'], unique=False)
    op.create_unique_constraint('uq_tv_episodes_season_id_episode_number', 'tv_episodes', ['season_id', 'episode_number'])
    op.add_column('tv_shows', sa.Column('seasons_checked_at', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_shows', 'seasons_checked_at')
    op.drop_constraint('uq_tv_episodes_season_id_episode_number', 'tv_episodes', type_='unique')
    op.drop_index('ix_tv_episodes_season_watched', table_name='tv_episodes')
    op.drop_index('ix_tv_episodes_air_at', table_name='tv_episodes', postgresql_where=sa.text('air_at IS NOT NULL'))
    op.drop_column('media_lists', 'position')
    op.drop_column('media_lists', 'pinned')
    op.drop_index(op.f('ix_games_parent_game_id'), table_name='games')
    op.drop_index('ix_cards_archive_number_user_active', table_name='cards', postgresql_where=sa.text('archive_number IS NOT NULL'))
    op.drop_constraint('uq_anime_episodes_season_id_episode_number', 'anime_episodes', type_='unique')
    op.drop_index('ix_anime_episodes_season_watched', table_name='anime_episodes')
    op.drop_index('ix_anime_episodes_air_at', table_name='anime_episodes', postgresql_where=sa.text('air_at IS NOT NULL'))
    op.drop_column('anime', 'title_native')
    op.drop_column('anime', 'title_romaji')
    op.drop_column('anime', 'title_english')
    op.drop_index('ix_calendar_events_user_date', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_table('job_settings')
    # ### end Alembic commands ###
