"""removed excess user rankings

Revision ID: 38e21782b991
Revises: de1f21b23297
Create Date: 2026-08-31 02:28:00.359301

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38e21782b991"
down_revision: Union[str, None] = "de1f21b23297"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "rating_enjoyment")
    op.drop_column("games", "rating_presentation")
    op.drop_column("games", "rating_confidence")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column(
            "rating_confidence",
            sa.NUMERIC(precision=4, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "games",
        sa.Column(
            "rating_presentation",
            sa.NUMERIC(precision=4, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "games",
        sa.Column(
            "rating_enjoyment", sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
