"""added fields to game

Revision ID: 48efa731484a
Revises: a7c4d91e2f08
Create Date: 2026-09-03 18:36:37.099455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48efa731484a'
down_revision: Union[str, None] = 'a7c4d91e2f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_platforms_game_id', table_name='game_platforms')
    op.add_column('games', sa.Column('how_long_to_beat', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('genre', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('games', sa.Column('took_to_beat', sa.Integer(), nullable=True))
    op.drop_constraint('fk_games_user_id_users', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('fk_games_user_id_users', 'games', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('games', 'took_to_beat')
    op.drop_column('games', 'genre')
    op.drop_column('games', 'how_long_to_beat')
    op.create_index('ix_game_platforms_game_id', 'game_platforms', ['game_id'], unique=False)
    # ### end Alembic commands ###
