"""added missing values

Revision ID: 98357cb173a4
Revises: e2ef918c2669
Create Date: 2026-09-02 04:09:19.887753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98357cb173a4'
down_revision: Union[str, None] = 'e2ef918c2669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('age_rating', sa.String(length=20), nullable=True))
    op.add_column('games', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('purchase_date', sa.BigInteger(), nullable=True))
    op.add_column('games', sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('games', sa.Column('purchase_price_currency_code', sa.String(length=3), nullable=True))
    op.add_column('games', sa.Column('physical_condition', sa.String(length=200), nullable=True))
    op.alter_column(
        'games',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.BigInteger(),
        existing_nullable=False,
        postgresql_using='EXTRACT(EPOCH FROM created_at)::BIGINT',
    )
    op.alter_column(
        'games',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.BigInteger(),
        existing_nullable=False,
        postgresql_using='EXTRACT(EPOCH FROM updated_at)::BIGINT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'games',
        'updated_at',
        existing_type=sa.BigInteger(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using='TO_TIMESTAMP(updated_at)::TIMESTAMPTZ',
    )
    op.alter_column(
        'games',
        'created_at',
        existing_type=sa.BigInteger(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using='TO_TIMESTAMP(created_at)::TIMESTAMPTZ',
    )
    op.drop_column('games', 'physical_condition')
    op.drop_column('games', 'purchase_price_currency_code')
    op.drop_column('games', 'purchase_price')
    op.drop_column('games', 'purchase_date')
    op.drop_column('games', 'source')
    op.drop_column('games', 'age_rating')
    op.drop_table('game_links')
    # ### end Alembic commands ###
