"""add provider identities and media playback history

Revision ID: a97470898855
Revises: f9c2a6d84103
Create Date: 2026-10-03 09:12:20.775006

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from src.database import migration_helpers as h

revision: str = "a97470898855"
down_revision: Union[str, None] = "f9c2a6d84103"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    h.create_table_if_missing(
        "media_provider_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("plugin_id", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_scope", sa.String(length=512), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.Column("media_type", sa.String(length=10), nullable=False),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applied_revision", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "plugin_id",
            "source",
            "source_scope",
            "external_id",
            name="uq_media_provider_identity",
        ),
    )
    h.create_index_if_missing(
        "ix_media_provider_target",
        "media_provider_links",
        ["user_id", "media_type", "media_id"],
        unique=False,
    )
    h.create_table_if_missing(
        "media_playback_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("link_id", sa.UUID(), nullable=False),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.Column("episode_external_id", sa.String(length=256), nullable=True),
        sa.Column("played_at", sa.BigInteger(), nullable=False),
        sa.Column("duration_seconds", sa.BigInteger(), nullable=True),
        sa.Column("provenance", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["link_id"], ["media_provider_links.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link_id", "external_id", name="uq_media_playback_event"),
    )
    h.create_index_if_missing(
        "ix_media_playback_history",
        "media_playback_events",
        ["user_id", "media_id", "played_at"],
        unique=False,
    )
    h.add_column_if_missing(
        "anime",
        sa.Column(
            "provider_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    h.add_column_if_missing(
        "movies",
        sa.Column(
            "provider_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    h.add_column_if_missing(
        "tv_shows",
        sa.Column(
            "provider_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tv_shows", "provider_ids")
    op.drop_column("movies", "provider_ids")
    op.drop_column("anime", "provider_ids")
    op.drop_index("ix_media_playback_history", table_name="media_playback_events")
    op.drop_table("media_playback_events")
    op.drop_index("ix_media_provider_target", table_name="media_provider_links")
    op.drop_table("media_provider_links")
    # ### end Alembic commands ###
