"""added folder requirement to game table

Revision ID: c7b57d2a26f3
Revises: 38e21782b991
Create Date: 2026-08-31 03:39:29.122561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b57d2a26f3'
down_revision: Union[str, None] = '38e21782b991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('folder_location', sa.String(length=150), nullable=False))
    op.create_unique_constraint(None, 'games', ['folder_location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'folder_location')
    # ### end Alembic commands ###
