"""create games table

Revision ID: de1f21b23297
Revises:
Create Date: 2026-08-31 02:03:33.235101

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de1f21b23297"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("developer", sa.String(length=200), nullable=True),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ABANDONED",
                "NOT_PLAYED",
                "PLAN_TO_PLAY",
                "ON_HOLD",
                "PLAYING",
                "PLAYED",
                "BEATEN",
                "COMPLETED",
                name="gamestatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("resume_note", sa.String(length=2000), nullable=True),
        sa.Column("playtime_seconds", sa.Integer(), nullable=False),
        sa.Column("rating_story", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_gameplay", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_soundtrack", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_presentation", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_enjoyment", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_overall", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_confidence", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("personal_rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    # ### end Alembic commands ###
