"""added series, tags, features

Revision ID: e2ef918c2669
Revises: c7b57d2a26f3
Create Date: 2026-08-31 18:42:12.826601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2ef918c2669'
down_revision: Union[str, None] = 'c7b57d2a26f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('series', sa.String(length=200), nullable=True))
    op.add_column(
        'games',
        sa.Column(
            'tags',
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text("ARRAY[]::VARCHAR[]"),
        ),
    )
    op.add_column(
        'games',
        sa.Column(
            'features',
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text("ARRAY[]::VARCHAR[]"),
        ),
    )
    op.alter_column('games', 'tags', server_default=None)
    op.alter_column('games', 'features', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'features')
    op.drop_column('games', 'tags')
    op.drop_column('games', 'series')
    # ### end Alembic commands ###
