"""Media

Revision ID: f186cf8aa5c4
Revises: f6bb4f914739
Create Date: 2026-09-21 03:56:51.021199

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from src.database import migration_helpers as h

# revision identifiers, used by Alembic.
revision: str = "f186cf8aa5c4"
down_revision: Union[str, None] = "f6bb4f914739"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Every step is create-if-missing: src/database/migrate.py runs this on
    # databases adopted from an older migration history, which already have
    # some or all of it. On an empty database it builds exactly what the
    # autogenerated version did.
    h.create_table_if_missing(
        "job_settings",
        sa.Column("job_id", sa.String(length=50), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("interval_minutes", sa.Integer(), server_default="1440", nullable=False),
        sa.Column("last_run_at", sa.BigInteger(), nullable=True),
        sa.Column("last_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
    )
    h.create_table_if_missing(
        "oidc_providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("issuer_url", sa.Text(), nullable=False),
        sa.Column("client_id", sa.String(length=256), nullable=False),
        sa.Column("client_secret", sa.Text(), nullable=False),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=True),
        sa.Column("groups_claim", sa.String(length=128), nullable=False),
        sa.Column("admin_group", sa.String(length=256), nullable=True),
        sa.Column("user_match_field", sa.String(length=16), nullable=False),
        sa.Column("allow_new_users", sa.Boolean(), nullable=False),
        sa.Column("button_text", sa.String(length=100), nullable=False),
        sa.Column("button_image_url", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    h.create_table_if_missing(
        "oidc_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_url", sa.Text(), nullable=True),
        sa.Column("client_id", sa.String(length=256), nullable=True),
        sa.Column("client_secret", sa.Text(), nullable=True),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=True),
        sa.Column("groups_claim", sa.String(length=128), nullable=False),
        sa.Column("admin_group", sa.String(length=256), nullable=True),
        sa.Column("user_match_field", sa.String(length=16), nullable=False),
        sa.Column("default_login_method", sa.String(length=16), nullable=False),
        sa.Column("login_button_text", sa.String(length=100), nullable=False),
        sa.Column("allow_new_users", sa.Boolean(), nullable=False),
        sa.Column("providers_json", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    h.create_table_if_missing(
        "calendar_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_time", sa.String(length=5), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("media_type", sa.String(length=10), nullable=True),
        sa.Column("media_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    h.create_index_if_missing(
        "ix_calendar_events_user_date", "calendar_events", ["user_id", "event_date"], unique=False
    )
    h.add_column_if_missing(
        "anime", sa.Column("title_english", sa.String(length=500), nullable=True)
    )
    h.add_column_if_missing(
        "anime", sa.Column("title_romaji", sa.String(length=500), nullable=True)
    )
    h.add_column_if_missing(
        "anime", sa.Column("title_native", sa.String(length=500), nullable=True)
    )
    h.create_index_if_missing(
        "ix_anime_episodes_air_at",
        "anime_episodes",
        ["air_at"],
        unique=False,
        postgresql_where=sa.text("air_at IS NOT NULL"),
    )
    h.create_index_if_missing(
        "ix_anime_episodes_season_watched", "anime_episodes", ["season_id", "watched"], unique=False
    )
    if not h.has_constraint("uq_anime_episodes_season_id_episode_number"):
        h.delete_duplicate_episodes("anime_episodes")
        op.create_unique_constraint(
            "uq_anime_episodes_season_id_episode_number",
            "anime_episodes",
            ["season_id", "episode_number"],
        )
    for column in (
        sa.Column("steamgriddb_api_key", sa.Text(), nullable=True),
        sa.Column("retroachievements_api_key", sa.Text(), nullable=True),
        sa.Column("giantbomb_api_key", sa.Text(), nullable=True),
        sa.Column("screenscraper_ssid", sa.String(length=128), nullable=True),
        sa.Column("screenscraper_sspassword", sa.Text(), nullable=True),
        sa.Column("screenscraper_devid", sa.String(length=128), nullable=True),
        sa.Column("screenscraper_devpassword", sa.Text(), nullable=True),
        sa.Column("xbox_client_id", sa.String(length=128), nullable=True),
        sa.Column("xbox_client_secret", sa.Text(), nullable=True),
    ):
        h.add_column_if_missing("app_integration_settings", column)
    h.create_index_if_missing(
        "ix_cards_archive_number_user_active",
        "cards",
        ["user_id", "archive_number"],
        unique=True,
        postgresql_where=sa.text("archive_number IS NOT NULL"),
    )
    h.add_column_if_missing("games", sa.Column("playnite_guid", sa.UUID(), nullable=True))
    h.drop_index_if_exists("ix_games_folder_location_active", "games")
    h.create_index_if_missing("ix_games_parent_game_id", "games", ["parent_game_id"], unique=False)
    h.create_index_if_missing("ix_games_playnite_guid", "games", ["playnite_guid"], unique=False)
    h.create_index_if_missing(
        "ix_games_user_folder_location_active",
        "games",
        ["user_id", "folder_location"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    h.add_column_if_missing(
        "media_lists", sa.Column("pinned", sa.Boolean(), server_default="false", nullable=False)
    )
    h.add_column_if_missing(
        "media_lists", sa.Column("position", sa.Integer(), server_default="0", nullable=False)
    )
    h.create_index_if_missing(
        "ix_tv_episodes_air_at",
        "tv_episodes",
        ["air_at"],
        unique=False,
        postgresql_where=sa.text("air_at IS NOT NULL"),
    )
    h.create_index_if_missing(
        "ix_tv_episodes_season_watched", "tv_episodes", ["season_id", "watched"], unique=False
    )
    if not h.has_constraint("uq_tv_episodes_season_id_episode_number"):
        h.delete_duplicate_episodes("tv_episodes")
        op.create_unique_constraint(
            "uq_tv_episodes_season_id_episode_number",
            "tv_episodes",
            ["season_id", "episode_number"],
        )
    h.add_column_if_missing(
        "tv_shows", sa.Column("seasons_checked_at", sa.BigInteger(), nullable=True)
    )
    h.add_column_if_missing(
        "users", sa.Column("oidc_subject", sa.String(length=512), nullable=True)
    )
    # named explicitly (Postgres's own default name for it) so the check
    # above can find it; the autogenerated version passed None
    h.create_unique_constraint_if_missing("users_oidc_subject_key", "users", ["oidc_subject"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_oidc_subject_key", "users", type_="unique")
    op.drop_column("users", "oidc_subject")
    op.drop_column("tv_shows", "seasons_checked_at")
    op.drop_constraint("uq_tv_episodes_season_id_episode_number", "tv_episodes", type_="unique")
    op.drop_index("ix_tv_episodes_season_watched", table_name="tv_episodes")
    op.drop_index(
        "ix_tv_episodes_air_at",
        table_name="tv_episodes",
        postgresql_where=sa.text("air_at IS NOT NULL"),
    )
    op.drop_column("media_lists", "position")
    op.drop_column("media_lists", "pinned")
    op.drop_index(
        "ix_games_user_folder_location_active",
        table_name="games",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_games_playnite_guid"), table_name="games")
    op.drop_index(op.f("ix_games_parent_game_id"), table_name="games")
    op.create_index(
        "ix_games_folder_location_active",
        "games",
        ["folder_location"],
        unique=True,
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_column("games", "playnite_guid")
    op.drop_index(
        "ix_cards_archive_number_user_active",
        table_name="cards",
        postgresql_where=sa.text("archive_number IS NOT NULL"),
    )
    op.drop_column("app_integration_settings", "xbox_client_secret")
    op.drop_column("app_integration_settings", "xbox_client_id")
    op.drop_column("app_integration_settings", "screenscraper_devpassword")
    op.drop_column("app_integration_settings", "screenscraper_devid")
    op.drop_column("app_integration_settings", "screenscraper_sspassword")
    op.drop_column("app_integration_settings", "screenscraper_ssid")
    op.drop_column("app_integration_settings", "giantbomb_api_key")
    op.drop_column("app_integration_settings", "retroachievements_api_key")
    op.drop_column("app_integration_settings", "steamgriddb_api_key")
    op.drop_constraint(
        "uq_anime_episodes_season_id_episode_number", "anime_episodes", type_="unique"
    )
    op.drop_index("ix_anime_episodes_season_watched", table_name="anime_episodes")
    op.drop_index(
        "ix_anime_episodes_air_at",
        table_name="anime_episodes",
        postgresql_where=sa.text("air_at IS NOT NULL"),
    )
    op.drop_column("anime", "title_native")
    op.drop_column("anime", "title_romaji")
    op.drop_column("anime", "title_english")
    op.drop_index("ix_calendar_events_user_date", table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_table("oidc_settings")
    op.drop_table("oidc_providers")
    op.drop_table("job_settings")
    # ### end Alembic commands ###
